name: Trigger auto deployment for netbox-progress

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/netbox-progress-AutoDeployTrigger-47332737-65e3-4270-8141-fede236ef714.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NETBOXPROGRESS_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: netboxfreshbuild.azurecr.io
          registryUsername: ${{ secrets.NETBOXPROGRESS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NETBOXPROGRESS_REGISTRY_PASSWORD }}
          containerAppName: netbox-progress
          resourceGroup: rg-josh-poc-001
          imageToBuild: netboxfreshbuild.azurecr.io/netbox-progress:${{ github.sha }}
          

     

